export const CURRENCY: {code: string, description: string}[] = [
{code: 'USD', description: 'United States Dollar' },
{code: 'EUR', description: 'Euro'},
{code: 'GBP', description: 'Great British Pound'},
{code: 'AED', description: 'Emirati dirham'},
{code: 'AFN', description: 'Afghan Afghani'},
{code: 'ALL', description: 'Albanian Lek '},
{code: 'AMD', description: 'Armenian Dram'},
{code: 'ANG', description: 'Dutch Guilder'},
{code: 'AOA', description: 'Angolan Kwanza'},
{code: 'ARS', description: 'Argentine Peso'},
{code: 'AUD', description: 'Australian Dollar'},
{code: 'AWG', description: 'Aruban Florin'},
{code: 'AZN', description: 'Azerbaijanian Manat'},
{code: 'BAM', description: 'Bosnia Convertible Mark'},
{code: 'BBD', description: 'Barbados Dollar'},
{code: 'BDT', description: 'Bangladeshi Taka'},
{code: 'BGN', description: 'Bulgarian Lev'},
{code: 'BIF', description: 'Burundi Franc'},
{code: 'BMD', description: 'Bermudian Dollar'},
{code: 'BND', description: 'Brunei Dollar'},
{code: 'BOB', description: 'Bolivian Boliviano'},
{code: 'BRL', description: 'Brazilian Real'},
{code: 'BSD', description: 'Bahamian Dollar'},
{code: 'BWP', description: 'Botswana Pula'},
{code: 'BZD', description: 'Belize Dollar'},
{code: 'CAD', description: 'Canadian Dollar'},
{code: 'CDF', description: 'Congolese Franc'},
{code: 'CHF', description: 'Swiss Franc'},
{code: 'CLP', description: 'Chilean Peso'},
{code: 'CNY', description: 'Chinese Yuan Renminbi'},
{code: 'COP', description: 'Colombian Peso'},
{code: 'CRC', description: 'Costa Rican Colón'},
{code: 'CVE', description: 'Cabo Verde Escudo'},
{code: 'CZK', description: 'Czech Koruna'},
{code: 'DJF', description: 'Djibouti Franc'},
{code: 'DKK', description: 'Danish Krone'},
{code: 'DOP', description: 'Dominican Peso'},
{code: 'DZD', description: 'Algerian Dinar'},
{code: 'EGP', description: 'Egyptian Pound'},
{code: 'ETB', description: 'Ethiopian Birr'},
{code: 'FJD', description: 'Fijian Dollar'},
{code: 'FKP', description: 'Falkland Islands Pound'},
{code: 'GEL', description: 'Georgian Lari'},
{code: 'GIP', description: 'Gibraltar Pound'},
{code: 'GMD', description: 'Gambian Dalasi'},
{code: 'GNF', description: 'Guinean Franc'},
{code: 'GTQ', description: 'Guatemalan Quetzal'},
{code: 'GYD', description: 'Guyanese Dollar'},
{code: 'HKD', description: 'Hong Kong Dollar'},
{code: 'HNL', description: 'Honduran Lempira'},
{code: 'HRK', description: 'Croatian Kuna'},
{code: 'HTG', description: 'Haitian Gourde'},
{code: 'HUF', description: 'Hungarian Forint'},
{code: 'IDR', description: 'Indonesian Rupiah'},
{code: 'ILS', description: 'New Israeli Sheqel'},
{code: 'INR', description: 'Indian Rupee'},
{code: 'ISK', description: 'Iceland Krona'},
{code: 'JMD', description: 'Jamaican Dollar'},
{code: 'JPY', description: 'Japanese Yen'},
{code: 'KES', description: 'Kenyan Shilling'},
{code: 'KGS', description: 'Kyrgyzstani Som'},
{code: 'KHR', description: 'Cambodian Riel'},
{code: 'KMF', description: 'Comoro Franc'},
{code: 'KRW', description: 'Korean Won'},
{code: 'KYD', description: 'Cayman Islands Dollar'},
{code: 'KZT', description: 'Kazakhstani Tenge'},
{code: 'LAK', description: 'Lao Kip'},
{code: 'LBP', description: 'Lebanese Pound'},
{code: 'LKR', description: 'Sri Lanka Rupee'},
{code: 'LRD', description: 'Liberian Dollar'},
{code: 'LSL', description: 'Basotho Loti'},
{code: 'MAD', description: 'Moroccan Dirham'},
{code: 'MDL', description: 'Moldovan Leu'},
{code: 'MGA', description: 'Malagasy Ariary'},
{code: 'MKD', description: 'Macedonian Denar'},
{code: 'MMK', description: 'Burmease Kyat'},
{code: 'MNT', description: 'Mongolian Tugrik'},
{code: 'MOP', description: 'Macau Pataca'},
{code: 'MRO', description: 'Mauritanian ougiya'},
{code: 'MUR', description: 'Mauritius Rupee'},
{code: 'MVR', description: 'Maldivian Rufiyaa'},
{code: 'MWK', description: 'Malawian Kwacha'},
{code: 'MXN', description: 'Mexican Peso'},
{code: 'MYR', description: 'Malaysian Ringgit'},
{code: 'MZN', description: 'Mozambican Metical'},
{code: 'NAD', description: 'Namibia Dollar'},
{code: 'NGN', description: 'Nigerian Naira'},
{code: 'NIO', description: 'Nicaraguan Córdoba'},
{code: 'NOK', description: 'Norwegian Krone'},
{code: 'NPR', description: 'Nepalese Rupee'},
{code: 'NZD', description: 'New Zealand Dollar'},
{code: 'PAB', description: 'Panamanian Balboa'},
{code: 'PEN', description: 'Peruvian Sol'},
{code: 'PGK', description: 'Papua New Guinean Kina'},
{code: 'PHP', description: 'Philippine Peso'},
{code: 'PKR', description: 'Pakistan Rupee'},
{code: 'PLN', description: 'Polish Złoty'},
{code: 'PYG', description: 'Paraguayan guaraní'},
{code: 'QAR', description: 'Qatari Rial'},
{code: 'RON', description: 'Romanian Leu'},
{code: 'RSD', description: 'Serbian Dinar'},
{code: 'RUB', description: 'Russian Ruble'},
{code: 'RWF', description: 'Rwandan Franc'},
{code: 'SAR', description: 'Saudi Arabian Riyal'},
{code: 'SBD', description: 'Solomon Islands Dollar'},
{code: 'SCR', description: 'Seychellois Rupee'},
{code: 'SEK', description: 'Swedish Krona'},
{code: 'SGD', description: 'Singapore Dollar'},
{code: 'SHP', description: 'Saint Helena Pound'},
{code: 'SLL', description: 'Sierra Leonean leone'},
{code: 'SOS', description: 'Somali Shilling'},
{code: 'SRD', description: 'Surinamese Dollar'},
{code: 'STD', description: 'Sao Tomean Dobra'},
{code: 'SZL', description: 'Swazi Lilangeni'},
{code: 'THB', description: 'Thai Baht'},
{code: 'TJS', description: 'Tajikistani Somoni'},
{code: 'TOP', description: 'Tongan Pa\'anga'},
{code: 'TRY', description: 'Turkish Lira'},
{code: 'TTD', description: 'Trinidad and Tobago Dollar'},
{code: 'TWD', description: 'New Taiwan Dollar'},
{code: 'TZS', description: 'Tanzanian Shilling'},
{code: 'UAH', description: 'Ukrainian Hryvnia'},
{code: 'UGX', description: 'Uganda Shilling'},
{code: 'UYU', description: 'Peso Uruguayo'},
{code: 'UZS', description: 'Uzbekistan Som'},
{code: 'VND', description: 'Vietnamese Dong'},
{code: 'VUV', description: 'Ni-Vanuatu Vatu'},
{code: 'WST', description: 'Samoan Tala'},
{code: 'XAF', description: 'CFA Franc BEAC'},
{code: 'XCD', description: 'Eastern Caribbean Dollar'},
{code: 'XOF', description: 'CFA Franc BCEAO'},
{code: 'XPF', description: 'CFP Franc'},
{code: 'YER', description: 'Yemeni Rial'},
{code: 'ZAR', description: 'Rand'},
{code: 'ZMW', description: 'Zambian Kwacha'}
]