export enum ActionTypes {
    GET_PLAYLIST_SECURITY_SETTINGS = "@@playlist_security/GET_PLAYLIST_SECURITY_SETTINGS",
    SAVE_PLAYLIST_SECURITY_SETTINGS = "@@playlist_security/SAVE_PLAYLIST_SECURITY_SETTINGS"
}