version: 0.2

#vars:
# STATE_BUCKET
# ENV_NAME_CLIENT
# ENV_NAME_ADMIN
# DOMAIN_NAME
# BRANCH
# GITHUB_TOKEN

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt update
      - apt install jq zip -y
      - git clone --branch $BRANCH https://$GITHUB_TOKEN@github.com/Dacast-Inc/dacast-backoffice-react.git
      - cd dacast-backoffice-react/deployment/deploy
      # - zip redirect.zip redirect.js
      # - zip admin.zip admin.js
      - ./terraform init -input=false -get=true -backend=true -backend-config="bucket=$STATE_BUCKET" -backend-config="key=$ENV_NAME_CLIENT-terraform-state"
      - ./terraform apply -auto-approve -var domain_name=$DOMAIN_NAME -var env_name_client=$ENV_NAME_CLIENT -var env_name_admin=$ENV_NAME_ADMIN
      - OUTPUT=$(./terraform output -json)
      - ARTIFACT_BUCKET=$(echo $OUTPUT | jq -r -e '.s3.value')
      - CLOUDFRONT_DISTRIBUTION_ID_CLIENT=$(echo $OUTPUT | jq -r -e '.distribution_id_client.value')
      - BASE_ASSETS_URL=$(echo $OUTPUT | jq -r -e '.base_url.value')
      - cd ../..
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd dist
      - echo $ARTIFACT_BUCKET
      - echo $ENV_NAME_CLIENT
      - echo $ENV_NAME_ADMIN
      - aws s3 sync . s3://$ARTIFACT_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_CLIENT --paths "/*"