export enum ActionTypes {
    GET_PLAYLIST_PAYWALL_INFOS = "@@playlist_paywall/GET_PLAYLIST_PAYWALL_INFOS",
    SAVE_PLAYLIST_PAYWALL_INFOS ="@@playlist_paywall/SAVE_PLAYLIST_PAYWALL_INFOS",
    CREATE_PLAYLIST_PRICE_PRESET = "@@playlist_paywall/CREATE_PLAYLIST_PRICE_PRESET",
    SAVE_PLAYLIST_PRICE_PRESET = "@@playlist_paywall/SAVE_PLAYLIST_PRICE_PRESET",
    DELETE_PLAYLIST_PRICE_PRESET = "@@playlist_paywall/DELETE_PLAYLIST_PRICE_PRESET",
    CREATE_PLAYLIST_PROMO_PRESET = "@@playlist_paywall/CREATE_PLAYLIST_PROMO_PRESET",
    SAVE_PLAYLIST_PROMO_PRESET = "@@playlist_paywall/SAVE_PLAYLIST_PROMO_PRESET",
    DELETE_PLAYLIST_PROMO_PRESET = "@@playlist_paywall/DELETE_PLAYLIST_PROMO_PRESET",

}