export const FeaturesDeveloperPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind'
]

export const FeaturesScalePlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels',
    'Video API'
]


export const FeaturesEventPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels'
]


export const FeaturesCustomPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels',
    'Video API',
    'White-label Cnames',
    'Multi-Level Access (beta)',
    'Customizable platform for resellers'
]

export const MainFeatures: {name: string; tooltip: string}[] = [
    {name: "Data", tooltip: "Data is consumed when viewers watch your content"},
    {name: "Storage", tooltip: "Storage is consumed by Video on Demand assets"},
    {name: "24/7 Phone Support", tooltip: "Call us at any time for personalised help and assistance"},
    {name: "Paywall", tooltip: "Sell your content vie Pay Per View or Subscription"},
    {name: "Ads", tooltip: "Monetise your content with Pre-, Mid- and Post-Roll Ads"},
    {name: "AES for VOD", tooltip: "AES Encryption helps prevent piracy and unauthorized downloading"},
    {name: "M3U8", tooltip: "A direct M3U8 link allows you to stream to TVs and other smart devices"},
    {name: "China", tooltip: "Our Premium delivery method with increased performance in China"},
]

export enum PlansName {
    "Developer" = "Developer Plan",
    "Event" = "Event Plan",
    "Annual Scale" = "Scale Plan",
    'Monthly Scale' = "Scale Plan"
}