export const FeaturesDeveloperPlan =[
    "Live Streaming",
    "Video On Demand Streaming",
    "Ad-free streaming",
    "24/7 Customer Support",
    "Unlimited simultaneous viewers",
    "Unlimited live channels",
    "Full 1080p HD Broadcasting",
    "Live Recording",
    "Mobile Device Support",
    "Embeddable HTML5 player",
    "Secure Delivery",
    "Real-Time Analytics",
    "Live & VOD Playlists",
    "VOD Chapter Markers",
    "Live Countdown",
    "30min Rewind",
    "Phone Support",
    "Paywall",
    "Multi-Bitrate VOD Streaming",
    "Pre, Mid & Post Roll Advertising",
    "Google Analytics Integration",
    "Advanced Library Management",
    "Responsive Video",
    "Video Availability Scheduling",
    "Player Customization",
    "Domain & Country Restriction",
    "Advanced Analytics"
]

export const FeaturesScalePlan =[
    "Live Streaming",
    "Video On Demand Streaming",
    "Ad-free streaming",
    "24/7 Customer Support",
    "Unlimited simultaneous viewers",
    "Unlimited live channels",
    "Full 1080p HD Broadcasting",
    "Live Recording",
    "Mobile Device Support",
    "Embeddable HTML5 player",
    "Secure Delivery",
    "Real-Time Analytics",
    "Live & VOD Playlists",
    "VOD Chapter Markers",
    "Live Countdown",
    "30min Rewind",
    "Phone Support",
    "Paywall",
    "Multi-Bitrate VOD Streaming",
    "Pre, Mid & Post Roll Advertising",
    "Google Analytics Integration",
    "Advanced Library Management",
    "Responsive Video",
    "Video Availability Scheduling",
    "Player Customization",
    "Domain & Country Restriction",
    "Advanced Analytics",
    "China Streaming for VOD"
]


export const FeaturesEventPlan =[
    "Live Streaming",
    "Video On Demand Streaming",
    "Ad-free streaming",
    "24/7 Customer Support",
    "Unlimited simultaneous viewers",
    "Unlimited live channels",
    "Full 1080p HD Broadcasting",
    "Live Recording",
    "Mobile Device Support",
    "Embeddable HTML5 player",
    "Secure Delivery",
    "Real-Time Analytics",
    "Live & VOD Playlists",
    "VOD Chapter Markers",
    "Live Countdown",
    "30min Rewind",
    "Phone Support",
    "Paywall",
    "Multi-Bitrate VOD Streaming",
    "Pre, Mid & Post Roll Advertising",
    "Google Analytics Integration",
    "Advanced Library Management",
    "Responsive Video",
    "Video Availability Scheduling",
    "Player Customization",
    "Domain & Country Restriction",
    "Advanced Analytics",
    "China Streaming for VOD"
]


export const FeaturesCustomPlan =[
    "Live Streaming",
    "Video On Demand Streaming",
    "Ad-free streaming",
    "24/7 Customer Support",
    "Unlimited simultaneous viewers",
    "Unlimited live channels",
    "Full 1080p HD Broadcasting",
    "Live Recording",
    "Mobile Device Support",
    "Embeddable HTML5 player",
    "Secure Delivery",
    "Real-Time Analytics",
    "Live & VOD Playlists",
    "VOD Chapter Markers",
    "Live Countdown",
    "30min Rewind",
    "Phone Support",
    "Paywall",
    "Multi-Bitrate VOD Streaming",
    "Pre, Mid & Post Roll Advertising",
    "Google Analytics Integration",
    "Advanced Library Management",
    "Responsive Video",
    "Video Availability Scheduling",
    "Player Customization",
    "Domain & Country Restriction",
    "Advanced Analytics",
    "China Streaming for VOD",
    "Customizable platform for resellers"
]

export const MainFeatures: {name: string; tooltip: string}[] = [
    {name: "Data", tooltip: "Data is consumed when viewers watch your content"},
    {name: "Storage", tooltip: "Storage is consumed by Video on Demand assets"},
    {name: "24/7 Phone Support", tooltip: "Call us at any time for personalised help and assistance"},
    {name: "Paywall", tooltip: "Sell your content vie Pay Per View or Subscription"},
    {name: "Ads", tooltip: "Monetise your content with Pre-, Mid- and Post-Roll Ads"},
    {name: "China", tooltip: "Our Premium delivery method with increased performance in China"},
]

export enum PlansName {
    "Developer" = "Developer Plan",
    "Event" = "Event Plan",
    "Annual Scale" = "Scale Plan",
    'Monthly Scale' = "Scale Plan"
}