export enum ActionTypes {
    GET_VOD_PAYWALL_INFOS = "@@vod_paywall/GET_VOD_PAYWALL_INFOS",
    SAVE_VOD_PAYWALL_INFOS ="@@vod_paywall/SAVE_VOD_PAYWALL_INFOS",
    CREATE_VOD_PRICE_PRESET = "@@vod_paywall/CREATE_VOD_PRICE_PRESET",
    SAVE_VOD_PRICE_PRESET = "@@vod_paywall/SAVE_VOD_PRICE_PRESET",
    DELETE_VOD_PRICE_PRESET = "@@vod_paywall/DELETE_VOD_PRICE_PRESET",
    GET_VOD_PAYWALL_PRICES = "@@vod_paywall/GET_VOD_PAYWALL_PRICES",
    CREATE_VOD_PROMO_PRESET = "@@vod_paywall/CREATE_VOD_PROMO_PRESET",
    SAVE_VOD_PROMO_PRESET = "@@vod_paywall/SAVE_VOD_PROMO_PRESET",
    DELETE_VOD_PROMO_PRESET = "@@vod_paywall/DELETE_VOD_PROMO_PRESET",
    GET_VOD_PAYWALL_PROMOS = "@@vod_paywall/GET_VOD_PAYWALL_PROMOS"
}