export const FeaturesDeveloperPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind'
]

export const FeaturesScalePlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels',
    'Video API'
]


export const FeaturesEventPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels'
]


export const FeaturesCustomPlan =[
    'White-label & Branding Control',
    'Ad-free streaming',
    '24/7 Customer Support',
    'Unlimited viewers',
    'Unlimited live channels',
    'Full 1080p HD Broadcasting',
    'Live Recording',
    'Mobile Device Support',
    'Embeddable HTML5 player',
    'Secure Delivery',
    'Geo restrictions',
    'Referrer restrictions',
    'Multi-Bitrate streaming',
    'FTP File Uploading',
    'Annual transcoding data ',
    'Real-Time Analytics',
    'Player API', 
    'iOS & Android SDKs',
    'Packages support live & VOD',
    'Looping playlist',
    'Chapter Markers (beta)',
    'Live Countdown',
    '30min Rewind',
    'Phone Support',
    'Ads Insertion',
    'Paywall',
    'M3u8 links for live channels',
    'Video API',
    'White-label Cnames',
    'Multi-Level Access (beta)',
    'Customizable platform for resellers'
]

export const MainFeatures: {name: string; tooltip: string}[] = [
    {name: "Data", tooltip: "Wtv"},
    {name: "Storage", tooltip: "Wtv"},
    {name: "24/7 Phone Support", tooltip: "Wtv"},
    {name: "Paywall", tooltip: "Wtv"},
    {name: "Ads", tooltip: "Wtv"},
    {name: "AES for VOD", tooltip: "Wtv"},
    {name: "M3u8", tooltip: "Wtv"},
    {name: "China", tooltip: "Wtv"},
]