export enum ActionTypes {
    GET_LIVE_PAYWALL_INFOS = "@@live_paywall/GET_LIVE_PAYWALL_INFOS",
    SAVE_LIVE_PAYWALL_INFOS ="@@live_paywall/SAVE_LIVE_PAYWALL_INFOS",
    CREATE_LIVE_PRICE_PRESET = "@@live_paywall/CREATE_LIVE_PRICE_PRESET",
    SAVE_LIVE_PRICE_PRESET = "@@live_paywall/SAVE_LIVE_PRICE_PRESET",
    DELETE_LIVE_PRICE_PRESET = "@@live_paywall/DELETE_LIVE_PRICE_PRESET",
    CREATE_LIVE_PROMO_PRESET = "@@live_paywall/CREATE_LIVE_PROMO_PRESET",
    SAVE_LIVE_PROMO_PRESET = "@@live_paywall/SAVE_LIVE_PROMO_PRESET",
    DELETE_LIVE_PROMO_PRESET = "@@live_paywall/DELETE_LIVE_PROMO_PRESET",

}