export enum ActionTypes {
    GET_CONTENT_SECURITY_SETTINGS = "@@content_security/GET_CONTENT_SECURITY_SETTINGS",
    SAVE_CONTENT_SECURITY_SETTINGS = "@@content_security/SAVE_CONTENT_SECURITY_SETTINGS",
    LOCK_CONTENT = "@@content_security/LOCK_CONTENT"
}